import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import styles from "./styles.module.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <Link className={styles.headerLink} href="/">
            <h1>TODOLIST</h1>
          </Link>
        </header>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
